language: objective-c
# xcode_project: WebView.xcodeproj
osx_image: xcode7.3
# xcode_scheme: WebView
before_install:
    - brew update
    - brew install xctool
script: xctool -project WebView.xcodeproj -scheme WebView test -test-sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
