language: objective-c
# xcode_project: WebView.xcodeproj
osx_image: xcode7.2
# xcode_scheme: WebView
before_install:
    - brew install xctool
    - xctool -v
script: xctool -project WebView.xcodeproj -scheme WebView test -test-sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
